env:
  app:
    pushSnsArns:
      android: ''
      ios: ''
    secrets:
      tokenKey:
        arn: arn:aws:ssm:us-west-2:207567754677:parameter/regional/token/key
        name: /regional/token/key
  branch: feature/install
  chatbot: null
  debug: 'false'
  deploy:
    auto: false
    website: false
  domain:
    hostedzone:
      id: ''
    name: ''
    sub:
      api:
        cert: ''
        name: ''
        path: /prod
        subdomain: ''
      device:
        apikey: VjZ5t6T9iy4oHMfHNF7LDok1T7HJ8eJl
        appid: mytaptrack
        cert: ''
        name: ''
        path: /prod
        subdomain: ''
      website:
        deploy: ''
        name: localhost:8000
        subdomain: ''
  name: dev
  region:
    primary: us-west-2
    regions: us-west-2
  regional:
    logging:
      bucket: mtt-207567754677-us-west-2-logs
    replication: 'true'
    templates:
      path: templates/
  sms:
    origin: ''
    secret: ''
  stacks:
    core: ''
  student:
    remove:
      timeout: 90
  system:
    email: nikody@advosight.com
  testing: null
  vpc: false
  website:
    google: null
    sign_up: true
    username: true
